FOR EACH ROW
BEGIN ATOMIC
	DELETE FROM Products.PRODUCTSYMBOLS WHERE Products.PRODUCTSYMBOLS.INSTR_ID = "OLD".INSTR_ID;
	DELETE FROM Products.PRODUCTDATA WHERE Products.PRODUCTDATA.INSTR_ID = "OLD".INSTR_ID;
END
