
CREATE VIEW productData (
	INSTR_ID string(10) NOT NULL,
	NAME string(60),
	TYPE string(15),
	ISSUER string(10),
	EXCHANGE string(10),
	ISDJI boolean NOT NULL OPTIONS(CASE_SENSITIVE 'FALSE', FIXED_LENGTH 'TRUE', SEARCHABLE 'ALL_EXCEPT_LIKE'),
	ISSP500 boolean NOT NULL OPTIONS(CASE_SENSITIVE 'FALSE', FIXED_LENGTH 'TRUE', SEARCHABLE 'ALL_EXCEPT_LIKE'),
	ISNAS100 boolean NOT NULL OPTIONS(CASE_SENSITIVE 'FALSE', FIXED_LENGTH 'TRUE', SEARCHABLE 'ALL_EXCEPT_LIKE'),
	ISAMEXINT boolean NOT NULL OPTIONS(CASE_SENSITIVE 'FALSE', FIXED_LENGTH 'TRUE', SEARCHABLE 'ALL_EXCEPT_LIKE'),
	PRIBUSINESS string(30),
	CONSTRAINT NAME_ACCESS ACCESSPATTERN (NAME)
) 
AS
	SELECT
	*
FROM
	Products.productdata;

